# postgresql-server : dbms
# python-psycopg2 : ansible postgres* modules needs psycopg2
- name: Install PostgreSQL
  yum: name="{{ item }}" state=present
  with_items:
    - "postgresql-server"
    - "python-psycopg2"
    - "postgresql-jdbc"
  when: (init is not defined) or (init)

- name: PostgreSQL initdb
  command:
    postgresql-setup initdb
  register:
    initdb_result
  failed_when: initdb_result.rc not in [0, 1]
  changed_when: initdb_result.rc == 0
  when: (init is not defined) or (init)

- name: change listen address
  lineinfile:
    dest=/var/lib/pgsql/data/postgresql.conf
    insertbefore="#listen_addresses = 'localhost'"
    line="listen_addresses = '*'"
  when: (init is not defined) or (init)

- name: append access settings
  lineinfile:
    dest=/var/lib/pgsql/data/pg_hba.conf
    insertafter="#[ ]+TYPE[ ]+DATABASE[ ]+USER[ ]+ADDRESS[ ]+METHOD"
    line={{ item }}
  with_items:
    - 'host    {{ db_name }}         {{ db_name }}         0.0.0.0/0               md5'
    - 'host    {{ db_name }}         {{ db_name }}         127.0.0.1/32            md5'
    - 'host    {{ db_name }}         {{ db_name }}         ::1/128                 md5'

- name: PostgreSQL service setup
  service:
    name=postgresql
    state=restarted
    enabled=yes

# There are no locale support other than en_US in Vagrant's CentOS7 image.
# We can put any unicode texts on the database even if encoding=en_US.UTF8.
# That's no problem.
- name: Create db
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name={{ db_name }}
    encoding='UTF8'
    lc_collate='en_US.UTF8'
    lc_ctype='en_US.UTF8'
    template='template0'

- name: Create user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    db={{ db_name }}
    name={{ db_name }}
    password={{ db_passwd }}
    priv=ALL
    state=present
    login_user=postgres
